# Generated by Django 5.0.6 on 2024-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='img/default_img/no_image_profile.jpg', upload_to='img/users_img/profile_pic'),
        ),
    ]
