# Generated by Django 5.0.6 on 2024-07-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proprietariostruttura',
            options={'verbose_name_plural': 'Proprietari Strutture'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='utente',
            options={'verbose_name_plural': 'Utenti'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
    ]
