# Generated by Django 5.0.6 on 2024-06-26 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sport', models.CharField(choices=[('tennis', 'Tennis'), ('calcio5', 'Calcio a 5'), ('calcio7', 'Calcio a 7'), ('padel', 'Padel'), ('beachvolley', 'Beach Volley'), ('pallavolo', 'Pallavolo')], max_length=50)),
                ('coperto', models.BooleanField(default=False)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'campi',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recensione', models.DateField()),
                ('testo', models.TextField()),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data_prenotazione', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('docce', 'Docce'), ('piscina', 'Piscina'), ('spogliatoi', 'Spogliatoi'), ('armadietti', 'Armadietti'), ('illuminazione', 'Illuminazione notturna'), ('bar', 'Bar'), ('parcheggio', 'Parcheggio gratuito'), ('noleggiorachette', 'Noleggio racchette'), ('casacche', 'Casacche in prestito')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_struttura', models.CharField(max_length=255)),
                ('citta', models.CharField(max_length=255)),
                ('indirizzo', models.CharField(max_length=255)),
                ('num_civico', models.IntegerField()),
                ('descrizione', models.TextField()),
                ('email', models.CharField(max_length=150)),
                ('numTelefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'strutture',
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campo')),
            ],
            options={
                'verbose_name_plural': 'prenotazioni',
            },
        ),
    ]
