# Generated by Django 5.0.6 on 2024-06-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.utente'),
        ),
        migrations.AddField(
            model_name='recensione',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='core.campo'),
        ),
        migrations.AddField(
            model_name='recensione',
            name='prenotazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='core.prenotazione'),
        ),
        migrations.AddField(
            model_name='recensione',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='users.utente'),
        ),
        migrations.AddField(
            model_name='campo',
            name='servizi',
            field=models.ManyToManyField(to='core.servizio'),
        ),
        migrations.AddField(
            model_name='recensione',
            name='struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='core.struttura'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.struttura'),
        ),
        migrations.AddField(
            model_name='campo',
            name='struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.struttura'),
        ),
        migrations.AlterUniqueTogether(
            name='recensione',
            unique_together={('utente', 'campo')},
        ),
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('campo', 'data', 'ora')},
        ),
    ]
