# Generated by Django 5.0.6 on 2024-06-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struttura',
            name='citta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='nome_struttura',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='numTelefono',
            field=models.CharField(max_length=13),
        ),
        migrations.AddConstraint(
            model_name='prenotazione',
            constraint=models.CheckConstraint(check=models.Q(('ora__hour__gte', 10), ('ora__hour__lt', 22), ('ora__minute', 0), ('ora__second', 0)), name='ora_intera_e_intervallo'),
        ),
    ]
