# Generated by Django 5.0.6 on 2024-06-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='img',
            field=models.ImageField(default='img/default_img/no_image.jpg', upload_to='img/users_img/'),
        ),
    ]
