# Generated by Django 5.0.6 on 2024-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='img',
            field=models.ImageField(default='img/default_img/no_image.jpg', upload_to='img/users_img/field_pic'),
        ),
    ]
