# Generated by Django 5.0.6 on 2024-06-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_struttura_citta_alter_struttura_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prenotazione',
            name='ora_intera_e_intervallo',
        ),
    ]
