# Generated by Django 5.0.6 on 2024-06-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_prenotazione_ora_intera_e_intervallo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struttura',
            name='citta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='nome_struttura',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='numTelefono',
            field=models.CharField(max_length=20),
        ),
    ]
