# Generated by Django 5.0.6 on 2024-06-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_struttura_citta_alter_struttura_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struttura',
            name='citta',
            field=models.CharField(max_length=100),
        ),
    ]
