# Generated by Django 5.0.6 on 2024-07-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_struttura_citta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={'verbose_name_plural': 'Campi'},
        ),
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='recensione',
            options={'verbose_name_plural': 'Recensioni'},
        ),
        migrations.AlterModelOptions(
            name='servizio',
            options={'verbose_name_plural': 'Servizi'},
        ),
        migrations.AlterModelOptions(
            name='struttura',
            options={'verbose_name_plural': 'Strutture'},
        ),
    ]
