# Generated by Django 5.0.6 on 2024-07-03 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_campo_options_alter_prenotazione_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='prenotazione',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recensione', to='core.prenotazione'),
        ),
    ]
