# Generated by Django 5.0.6 on 2024-07-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_recensione_prenotazione'),
        ('users', '0002_alter_proprietariostruttura_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campo'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.struttura'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.utente'),
        ),
    ]
